version: '3.8'

services:
    # dev:
    #     container_name: serai_code_test_backend_dev
    #     image: serai-code-test-backend-dev:1.0.0
    #     build:
    #         context: .
    #         target: development
    #         dockerfile: ./Dockerfile
    #     command: npm run start:debug
    #     ports:
    #         - 3002:3002
    #         - 9229:9229
    #     networks:
    #         - nesjs-network
    #     volumes:
    #         - .:/usr/src/app
    #         - /usr/src/app/node_modules
    #     restart: unless-stopped
    prod:
        container_name: serai_code_test_backend_prod
        image: serai-code-test-backend-prod:1.0.0
        build:
            context: .
            target: production
            dockerfile: ./Dockerfile
        command: npm run start:prod
        ports:
            - 3001:3001
            - 9229:9229
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped

networks:
    nesjs-network: